 export const siteData = [
    {
      imageUrl: '/photos/williamHill.png',   
      bonusData: 'Up to $500 bonus',
      bonusCode: 'GOLF2024',
      reviewLink: '',
      tournamentBonus: 'Yes',
      cashOut: 'No',
      boostedOdds: 'Yes',
      bonus: 'Yes',
      inPlayBetting: 'No',
      liveStreaming: 'Yes',
      starRating: 4.5,
      paymentMethods: [
        '/Payment/70606_discover_straight_icon.png',
        '/Payment/206681_payment_bitcoin_method_icon.png',
        '/Payment/206683_wallet_google_method_payment_icon.png',
        '/Payment/206684_visa_method_card_payment_icon.png',
        '/Payment/1933704_american-express_amex_charge_credit card_payment_icon.png',
        '/Payment/2629972_card_cash_checkout_credit_mastercard_icon.png',
      ]
    },
    {
      imageUrl: '/photos/williamHill.png',   
      bonusData: 'Up to $500 bonus',
      bonusCode: 'GOLF2024',
      reviewLink: '',
      tournamentBonus: 'Yes',
      cashOut: 'No',
      boostedOdds: 'Yes',
      bonus: 'Yes',
      inPlayBetting: 'No',
      liveStreaming: 'Yes',
      starRating: 4.5,
      paymentMethods: [
        '/Payment/70606_discover_straight_icon.png',
        '/Payment/206681_payment_bitcoin_method_icon.png',
        '/Payment/206683_wallet_google_method_payment_icon.png',
        '/Payment/206684_visa_method_card_payment_icon.png',
        '/Payment/1933704_american-express_amex_charge_credit card_payment_icon.png',
        '/Payment/2629972_card_cash_checkout_credit_mastercard_icon.png',
      ]
    },
    {
      imageUrl: '/photos/williamHill.png',   
      bonusData: 'Up to $500 bonus',
      bonusCode: 'GOLF2024',
      reviewLink: '',
      tournamentBonus: 'Yes',
      cashOut: 'No',
      boostedOdds: 'Yes',
      bonus: 'Yes',
      inPlayBetting: 'No',
      liveStreaming: 'Yes',
      starRating: 4.5,
      paymentMethods: [
        '/Payment/70606_discover_straight_icon.png',
        '/Payment/206681_payment_bitcoin_method_icon.png',
        '/Payment/206683_wallet_google_method_payment_icon.png',
        '/Payment/206684_visa_method_card_payment_icon.png',
        '/Payment/1933704_american-express_amex_charge_credit card_payment_icon.png',
        '/Payment/2629972_card_cash_checkout_credit_mastercard_icon.png',
      ]
    },
    {
      imageUrl: '/photos/williamHill.png',   
      bonusData: 'Up to $500 bonus',
      bonusCode: 'GOLF2024',
      reviewLink: '',
      tournamentBonus: 'Yes',
      cashOut: 'No',
      boostedOdds: 'Yes',
      bonus: 'Yes',
      inPlayBetting: 'No',
      liveStreaming: 'Yes',
      starRating: 4.5,
      paymentMethods: [
        '/Payment/70606_discover_straight_icon.png',
        '/Payment/206681_payment_bitcoin_method_icon.png',
        '/Payment/206683_wallet_google_method_payment_icon.png',
        '/Payment/206684_visa_method_card_payment_icon.png',
        '/Payment/1933704_american-express_amex_charge_credit card_payment_icon.png',
        '/Payment/2629972_card_cash_checkout_credit_mastercard_icon.png',
      ]
    }
]